#!/usr/bin/env bash
set -x

pid=0

term_handler() {
  rm -f /opt/consul/conf/aws-proxy-consul.json
  rm -f /etc/goss/aws-proxy-goss.yaml  
  
  if [ $pid -ne 0 ]; then
    kill -TERM "$pid"
    wait "$pid"
  fi
  exit 143; # 128 + 15 -- TERM
}

trap 'kill ${!}; term_handler' TERM

mv /var/aws-proxy-consul.json /opt/consul/conf/aws-proxy-consul.json
mv /var/aws-proxy-goss.yaml /etc/goss/aws-proxy-web-goss.yaml

java -Djava.security.egd=file:/dev/./urandom -jar /app.jar

pid="$!"

tail -f /dev/null & wait ${!}